/*
 * Copyright 2019-2025 JetBrains s.r.o. and contributors.
 * Use of this source code is governed by the Apache 2.0 License that can be found in the LICENSE.txt file.
 */

package kotlinx.datetime

import kotlinx.datetime.JvmSerializableClassesTest.SerCl.Pattern.*
import org.junit.Test
import java.io.*
import java.lang.reflect.Member
import java.lang.reflect.Method
import java.lang.reflect.Modifier.*
import java.nio.file.FileSystems
import java.nio.file.FileVisitResult
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.SimpleFileVisitor
import java.nio.file.attribute.BasicFileAttributes
import kotlin.io.path.Path
import kotlin.reflect.KClass
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

class JvmSerializableClassesTest {

    // not including enums and references (subtypes of kotlin.jvm.internal.FunctionReferenceImpl or
    // kotlin.jvm.internal.MutablePropertyReference[0/1]Impl)
    @Suppress("RemoveRedundantQualifierName")
    private val serializableClasses = listOf(
        SerCl(kotlinx.datetime.LocalDate::class, 7026816023079564263L, PROXIED),
        SerCl(kotlinx.datetime.LocalDateTime::class, -4261744960416354711L, PROXIED), // todo
        SerCl(kotlinx.datetime.LocalTime::class, -352249606036216323L, PROXIED), // todo
        SerCl(kotlinx.datetime.UtcOffset::class, -6636773355667981618L, PROXIED), // todo
        SerCl(kotlinx.datetime.Ser::class, 0L, PROXY),
        SerCl(kotlinx.datetime.DateTimeArithmeticException::class, -3207806170214997982L, EXCEPTION),
        SerCl(kotlinx.datetime.IllegalTimeZoneException::class, 1159315966274264801L, EXCEPTION),
        SerCl(kotlinx.datetime.DateTimeFormatException::class, 4231196759387994100L, EXCEPTION),
        SerCl(kotlinx.datetime.internal.format.parser.ParseException::class, 5691186997393344103L, EXCEPTION),
    )

    private data class SerCl(
        val clazz: KClass<out Serializable>,
        val expectedSerialVersionUID: Long,
        val pattern: Pattern,
    ) {
        enum class Pattern {
            /** @see JvmSerializableClassesTest.checkProxy */
            PROXY,

            /** @see JvmSerializableClassesTest.checkProxied */
            PROXIED,

            /** @see JvmSerializableClassesTest.checkException */
            EXCEPTION, // todo split this up?
        }
    }

    @Test
    fun foo() {
        serializableClasses.forEach { (clazz, expectedSerialVersionUID, mode) ->
            val javaClass = clazz.java
            javaClass.checkIs<Serializable>()
            javaClass.checkDeclaresSerialVersionUID(expectedSerialVersionUID)
            javaClass.checkDoesntDeclareSerialPersistentFields()
            when (mode) {
                PROXY -> javaClass.checkProxy()
                PROXIED -> javaClass.checkProxied()
                EXCEPTION -> javaClass.checkException()
            }
        }
    }

    private inline fun <reified T> Class<out Serializable>.checkIs() {
        assertTrue(
            T::class.java.isAssignableFrom(this),
            message = "$this is no longer a subtype of ${T::class.simpleName}. You might want to adjust " +
                "JvmSerializableClassesTest.",
        )
    }

    private fun Member.checkModifiers(vararg expectedModifiers: Int) {
        var expected = expectedModifiers.fold(0, Int::or)
        var actual = modifiers
        if (isPrivate(expected) && this is Method) {
            // kotlin adds final to private methods, ignore it
            expected = expected and FINAL.inv()
            actual = actual and FINAL.inv()
        }
        assertEquals(
            expected, actual,
            message = "$declaringClass: $name must be '${toString(expected)}' but was '${toString(actual)}'.",
        )
    }

    private fun Class<out Serializable>.checkDeclaresMethod(
        name: String,
        returnType: Class<*>,
        vararg parameterTypes: Class<*>,
    ): Method {
        // don't use getDeclaredMethod(String name, Class<?>... parameterTypes), it can't handle multiple methods with
        // the same parameter types but a different return type as would be generated by code like this:
        // fun a(): Int = 0
        // @JvmName("a") fun b(): Long = 0
        declaredMethods
            .filter { it.name == name }
            .ifEmpty { fail("$this is missing $name. Was it misspelled?") }
            .firstOrNull { it.returnType == returnType && it.parameterTypes.contentEquals(parameterTypes) }
            ?.let { return it }

        val params = parameterTypes.joinToString { it.kotlin.simpleName.toString() }
        val sig = "fun $name($params): ${returnType.kotlin.simpleName}"
        if (returnType.isPrimitive) fail("$this has a wrong signature for $name, must be $sig")
        fail("$this has a wrong signature for $name, must be $sig or $sig?")
    }


    private fun Method.checkThrows(vararg expectedExceptionTypes: Class<out Exception>) {
        assertEquals(
            expectedExceptionTypes.toSet(), actual = exceptionTypes.toSet(),
            message = "$declaringClass: $name throws the wrong exception types."
        )
    }

    private fun Class<out Serializable>.checkDeclaresSerialVersionUID(expectedSerialVersionUID: Long) {
        // ANY-ACCESS-MODIFIER static final long serialVersionUID = 42L;
        val serialVersionUID = try {
            getDeclaredField("serialVersionUID")
        } catch (e: NoSuchFieldException) {
            fail(
                message = "$this is missing serialVersionUID. All serializable classes should explicitly declare " +
                    "their serialVersionUID. See " +
                    "https://docs.oracle.com/en/java/javase/24/docs/specs/serialization/class.html#stream-unique-identifiers",
                cause = e,
            )
        }
        // private is not strictly required TODO ref / explanation
        serialVersionUID.checkModifiers(PRIVATE, STATIC, FINAL)
        assertEquals(
            expected = java.lang.Long.TYPE, actual = serialVersionUID.type,
            message = "$this: serialVersionUID must be long.",
        )

        serialVersionUID.isAccessible = true
        assertEquals(
            expectedSerialVersionUID, actual = serialVersionUID.get(null),
            message = "$this: serialVersionUID changed. This means trying to deserialize previously serialized " +
                "instances of this class will now fail with InvalidClassException. Try versioning this class " +
                "differently instead. See " +
                "https://docs.oracle.com/en/java/javase/24/docs/specs/serialization/version.html",
        )
    }

    private fun Class<out Serializable>.checkDoesntDeclareSerialPersistentFields() {
        try {
            getDeclaredField("serialPersistentFields")
        } catch (_: NoSuchFieldException) {
            return // expected
        }
        if (Externalizable::class.java.isAssignableFrom(this)) {
            fail(
                "$this declares serialPersistentFields. This field is ignored for classes that implement " +
                    "Externalizable. It can safely be removed."
            )
        } else {
            fail(
                // TODO
                """
                $this: Java Object Serialization should.
                
                See JvmSerializableClassesTest for the patterns that should be used to implement Java Object Serialization.
            """.trimIndent()
            )
        }
    }

    private fun Class<out Serializable>.checkDoesntHaveMethod(name: String, reason: String) {
        // don't bother to check the signature, this might lead to false positives though
        if (declaredMethods.any { it.name == name }) {
            fail("$this declares $name. $reason")
        }
    }

    /**
     * Check the TODO java ser
     *
     * ```
     * @PublishedApi // keep it in the ABI dump to ensure the name of the class isn't changed
     * internal class SerializationProxy internal constructor(...) : java.io.Externalizable {
     *
     *     // public no-arg constructor used by deserialization
     *     constructor() : this(...)
     *
     *     override fun writeExternal(oo: java.io.ObjectOutput) {
     *         // ...
     *         TODO()
     *     }
     *
     *     override fun readExternal(oi: java.io.ObjectInput) {
     *         // ...
     *         TODO()
     *     }
     *
     *     // might also return Any?
     *     @Throws(java.io.ObjectStreamException::class)
     *     private fun readResolve(): Any = SerializationProxied(...)
     *
     *     private companion object {
     *         private const val serialVersionUID: Long = 0L
     *     }
     * }
     * ```
     *
     * @see kotlinx.datetime.Ser
     */
    private fun Class<out Serializable>.checkProxy() {
        checkIs<Externalizable>()

        val noArgConstructor = try {
            getDeclaredConstructor()
        } catch (e: NoSuchMethodException) {
            fail(
                message = "$this does not declare the no-arg constructor which required for classes that implement " +
                    "Externalizable.",
                cause = e
            )
        }
        noArgConstructor.checkModifiers(PUBLIC)

        // Don't check writeExternal and readExternal, the compiler already does that. They are just normal abstract
        // interface methods and must be overridden by classes that implement Externalizable.

        // ANY-ACCESS-MODIFIER Object readResolve() throws ObjectStreamException;
        val readResolve = checkDeclaresMethod("readResolve", Object::class.java)
        // private is not strictly required TODO ref / explanation
        readResolve.checkModifiers(PRIVATE)
        readResolve.checkThrows(ObjectStreamException::class.java)

        checkDoesntHaveMethod(
            "writeReplace",
            reason = "It is unlikely that a serialization proxy needs to replace itself during serialization. If it " +
                "does, you might want to adjust JvmSerializableClassesTest.",
        )

        val ignoredReason =
            "This method is ignored for classes that implement Externalizable. It can safely be removed."
        checkDoesntHaveMethod("writeObject", ignoredReason)
        checkDoesntHaveMethod("readObject", ignoredReason)
        checkDoesntHaveMethod("readObjectNoData", ignoredReason)
    }

    /**
     * TODO
     *
     * ```
     * class SerializationProxied(...) : java.io.Serializable {
     *
     *     @Throws(java.io.IOException::class, java.lang.ClassNotFoundException::class)
     *     private fun readObject(ois: java.io.ObjectInputStream): Unit =
     *         throw java.io.InvalidObjectException("SerializationProxied must be deserialized via SerializationProxy")
     *
     *     // might also return Any?
     *     @Throws(java.io.ObjectStreamException::class)
     *     private fun writeReplace(): Any = SerializationProxy(this)
     *
     *     private companion object {
     *         // even though this class uses writeReplace, a stable serialVersionUID means exceptions caused by
     *         // deserialization of malicious streams will be consistent (InvalidClassException vs.
     *         // InvalidObjectException, see JvmSerializationTest.fooBar)
     *         private const val serialVersionUID: Long = 0L
     *     }
     * }
     * ```
     *
     * ```
     * open class ExtendableSerializationProxied(...) : java.io.Serializable {
     *
     *     @Throws(java.io.IOException::class, java.lang.ClassNotFoundException::class)
     *     private fun readObject(ois: java.io.ObjectInputStream): Unit = throw java.io.InvalidObjectException(
     *         "ExtendableSerializationProxied must be deserialized via SerializationProxy"
     *     )
     *
     *     @Throws(java.io.ObjectStreamException::class)
     *     private fun readObjectNoData(): Unit = TODO("what do we do here?")
     *
     *     // might also return Any?
     *     @Throws(java.io.ObjectStreamException::class)
     *     private fun writeReplace(): Any = SerializationProxy(this)
     *
     *     private companion object {
     *         // even though this class uses writeReplace, a stable serialVersionUID means exceptions caused by
     *         // deserialization of malicious streams will be consistent (InvalidClassException vs.
     *         // InvalidObjectException, see JvmSerializationTest.fooBar)
     *         private const val serialVersionUID: Long = 0L
     *     }
     * }
     * ```
     *
     * @see kotlinx.datetime.LocalDate
     */
    private fun Class<out Serializable>.checkProxied() {
        // ANY-ACCESS-MODIFIER Object writeReplace() throws ObjectStreamException;
        val writeReplace = checkDeclaresMethod("writeReplace", Object::class.java)
        // private is not strictly required TODO ref / explanation
        writeReplace.checkModifiers(PRIVATE)
        writeReplace.checkThrows(ObjectStreamException::class.java)

        // private void readObject(java.io.ObjectInputStream in) throws IOException, ClassNotFoundException;
        // todo explain (always throw)
        val readObject = checkDeclaresMethod("readObject", Void.TYPE, ObjectInputStream::class.java)
        readObject.checkModifiers(PRIVATE)
        readObject.checkThrows(IOException::class.java, ClassNotFoundException::class.java)

        if (isFinal(modifiers)) {
            checkDoesntHaveMethod(
                "readObjectNoData",
                reason = "This method is ignored for classes that can't be extended. It can safely be removed.",
            )
        } else {
            // private void readObjectNoData() throws ObjectStreamException;
            val readObjectNoData = checkDeclaresMethod("readObjectNoData", Void.TYPE)
            readObjectNoData.checkModifiers(PRIVATE)
            readObjectNoData.checkThrows(ObjectStreamException::class.java)
        }

        // todo is this true?
        checkDoesntHaveMethod(
            "writeObject",
            reason = "This method is ignored for classes that declare a writeReplace method. It can safely be removed.",
        )
        checkDoesntHaveMethod(
            "readResolve",
            reason = "It is unlikely that a proxied class needs to replace itself during deserialization. If it " +
                "does, you might want to adjust JvmSerializableClassesTest.",
        )
    }

    /**
     * TODO
     *
     * Some examples of common serialization patterns for exceptions:
     *
     * ```
     * open class BoringException : RuntimeException {
     *     constructor() : super()
     *     constructor(message: String?) : super(message)
     *     constructor(message: String?, cause: Throwable?) : super(message, cause)
     *     constructor(cause: Throwable?) : super(cause)
     *
     *     private companion object {
     *         private const val serialVersionUID: Long = 0L
     *     }
     * }
     * ```
     *
     * ```
     * class WrapperException(cause: WrappedException) : RuntimeException(cause) {
     *
     *     override val cause: WrappedException get() = super.cause as WrappedException
     *
     *     @Throws(java.io.IOException::class, java.lang.ClassNotFoundException::class)
     *     private fun readObject(ois: java.io.ObjectInputStream) {
     *         ois.defaultReadObject()
     *         // or otherwise ensure invariants are not violated
     *         if (super.cause !is WrappedException) {
     *             throw java.io.InvalidObjectException("WrapperException.cause must be WrappedException")
     *         }
     *     }
     *
     *     // todo readObjectNoData needed (if this class was open)?
     *
     *     private companion object {
     *         private const val serialVersionUID: Long = 0L
     *     }
     * }
     * ```
     *
     * ```
     * class ExceptionWithData(
     *     message: String?,
     *     cause: Throwable?,
     *     data1: SomeData,
     *     data2: OtherData,
     * ) : RuntimeException(message, cause) {
     *
     *     // the name of this field is now part of the public API via serialization
     *     private val d: SomeData? = data1
     *
     *     public val data1: SomeData get() = d!!
     *
     *     // this field will be null after deserialization
     *     @kotlin.jvm.Transient
     *     public val data2: OtherData? = data2
     *
     *     @Throws(java.io.IOException::class, java.lang.ClassNotFoundException::class)
     *     private fun readObject(ois: java.io.ObjectInputStream) {
     *         ois.defaultReadObject()
     *         // or otherwise ensure invariants are not violated
     *         if (d == null) {
     *             throw java.io.InvalidObjectException("ExceptionWithData.d must not be null")
     *         }
     *     }
     *
     *     // todo same here with readObjectNoData
     *
     *     private companion object {
     *         private const val serialVersionUID: Long = 0L
     *     }
     * }
     * ```
     *
     * @see java.io.UncheckedIOException
     */
    private fun Class<out Serializable>.checkException() {
        checkIs<Throwable>()
        if (declaredFields.any { !isStatic(it.modifiers) }) {
            TODO()
        } else {
            val notNeededReason =
                "This method is not needed for exception classes with no fields. It can safely be removed."
            checkDoesntHaveMethod("writeObject", notNeededReason)
            // todo if readObject or readObjectNoData present, check for correct signature
//            checkDoesntHaveMethod("readObject", notNeededReason)
//            checkDoesntHaveMethod("readObjectNoData", notNeededReason) // todo only if not final
            checkDoesntHaveMethod("writeReplace", notNeededReason)
            checkDoesntHaveMethod("readResolve", notNeededReason)
        }
    }
}


private val printSerializableClasses = object : SimpleFileVisitor<Path>() {
    override fun visitFile(file: Path, attrs: BasicFileAttributes): FileVisitResult {
        val fileName = file.fileName.toString()
        if (!fileName.endsWith(".class") || fileName == "module-info.class") {
            return FileVisitResult.CONTINUE
        }
        val binaryName = buildString {
            file.parent?.forEach { append(it).append('.') }
            append(fileName, 0, fileName.lastIndexOf('.'))
        }
        val currentLoader = javaClass.classLoader
        val clazz = Class.forName(binaryName, false, currentLoader)
        if (!Serializable::class.java.isAssignableFrom(clazz) || Enum::class.java.isAssignableFrom(clazz)) {
            return FileVisitResult.CONTINUE
        }
        print("${clazz.name} extends ${clazz.superclass.name}")
        val interfaces = clazz.interfaces
        if (interfaces.size > 0) {
            print(interfaces.joinToString(", ", " implements ") { it.name })
        }
        println()
        return FileVisitResult.CONTINUE
    }
}

fun main(vararg args: String) {
    val jar = Path(args[0])
    FileSystems.newFileSystem(jar, null as ClassLoader?).use { fs ->
        fs.rootDirectories.forEach { root -> Files.walkFileTree(root, printSerializableClasses) }
    }
}
